### ISSUE TITLE
Install doc for tests recommandation 

### ISSUE THREAD

**Issue by meteospike** [ecmwf-ifs/loki#102]
At the end of the manual installation, the documentation recommands to run `py.test` from the root directory.
But then pytest will load both `tests/conftest.py` and `transformations/test/conftest.py`, without hierarchical, and I may be wrong but it seems that this leads to some incohenrency.
Either we could change the doc (move to each directory), either we create a coherent set of tests with hierarchical conftest.

**Comment by reuterbal** [comment]
Thanks, the documentation is indeed out of date there and a plain call to py.test leads to conflicts.
While there is certainly scope for refactoring some of the conftest functionality, tests for transformations, lint_rules and the core loki tool should be called separately. This can simply be done as follows:

```
py.test tests
py.test transformations
py.test lint_rules
```

I will clarify the instruction.

**Comment by reuterbal** [comment]
This is related to #33
