### ISSUE TITLE
Prevent multiple values conflict in FindExpressionRoot init

### ISSUE THREAD

**Issue by meteospike** [ecmwf-ifs/loki#120]
In module `loki.expression.expr_visitors` the initialization of class `FindExpressionRoot` does not check for `unique` keyword argument presence, which could lead to a multiple values conflict since this argument is statically set in the `super.__init__`  call.

This could be easily fixed, adding the line:
`kwargs.pop('unique', None)`

**Comment by reuterbal** [comment]
Thanks a lot for reporting, this is a genuine bug and I agree on the fix. I'll implement it now
