### ISSUE TITLE
FortranCodegen can't output SAVE attribute

### ISSUE THREAD

**Issue by quepas** [ecmwf-ifs/loki#164]
Given the simplest example code `test.f90`:
```fortran
MODULE test
  INTEGER, SAVE, ALLOCATABLE, POINTER :: variable
END MODULE test
```
And parsing-regenerating code in Loki:
```python
from loki import Sourcefile
s = Sourcefile.from_file("test.f90")
print(s.to_fortran(conservative=False))
```
We can observe, that the `SAVE` attribute is not written back by the `FortranCodegen`, as opposed to `ALLOCATABLE` and `POINTER`.
```fortran
MODULE test
  INTEGER, ALLOCATABLE, POINTER :: variable ! Missing SAVE
END MODULE test
```
There is a quick solution I applied on my fork: https://github.com/quepas/loki/commit/09cbd09bf1dcff661388544b8eecae50f5a13f7f

If you would like to, I can transform my branch into a pull request!

**Comment by reuterbal** [comment]
Thank you very much for reporting this. I have taken your commit and added a test and submitted this in #165.
