### ISSUE TITLE
Crash when using hoist mode in the SCC transform, related to variables declarations

### ISSUE THREAD

**Issue by JoeffreyLegaux** [ecmwf-ifs/loki#25]
During an SCC transformation using the hoist mode, the process crashes when converting the source object to an actual file.
Samples of the error message :
```
.....
File "/home/legaux/meteo/loki_github/loki/transform/transformation.py", line 136, in apply_file
    self.transform_file(sourcefile, **kwargs)
  File "/home/legaux/meteo/loki_github/loki/transform/build_system_transform.py", line 148, in transform_file
    sourcefile.write(path=sourcepath)
  File "/home/legaux/meteo/loki_github/loki/sourcefile.py", line 521, in write
    source = self.to_fortran(conservative, cuf) if source is None else source
....
  File "/home/legaux/meteo/loki_github/loki/backend/fgen.py", line 140, in visit
    return super().visit(o, *args, **kwargs)
  File "/home/legaux/meteo/loki_github/loki/visitors/visitor.py", line 124, in visit
    return meth(o, *args, **kwargs)
  File "/home/legaux/meteo/loki_github/loki/backend/fgen.py", line 338, in visit_VariableDeclaration
    assert all(t.compare(types[0], ignore=ignore) for t in types)
AssertionError  
```

Reproducer for the bug : https://mercure.cerfacs.fr/cfxfile/get.php?614e213652fa

The issue seems to come from the fact that tere are in the same declaration variables that use the vertical variable (KLEV) while others don't. 
If line 138 in acdrag.F90 is commented and replaced with the next (currently commented) declaration where the two kind of variables are separated, the scripts does not crash.
The variables number of dimensions, shape, demotion uring the transformation or even actual usage in the routine do not seem to have an impact (cfr line 155 : two dummy 1D arrays produce the same error if uncommented).

**Comment by reuterbal** [comment]
Hi Joeffrey, thanks for the report and apologies for the late reaction to this. If you can, would you be able to re-share the reproducer? I thought I had downloaded it but can't find it anymore and the link has expired now.

I believe that issue has not been fixed, yet, however you might be able to add this yourself quickly with the recently add [single_variable_declaration](https://github.com/ecmwf-ifs/loki/blob/a2403d5572e033cf8a72a18b688a6d374bcf7d2a/loki/transform/transform_utilities.py#L35) utility, which should allow you to convert the declarations into a safe format.

**Comment by JoeffreyLegaux** [comment]
Hi Balthasar, here is a new upload of the reproducer : https://mercure.cerfacs.fr/cfxfile/share.php?sr=67d7bd70e4e0

Thaks for the utility function, it shall be helpful indeed.

**Comment by reuterbal** [comment]
Hi Joeffrey, apologies for not acting on this earlier. I just tested the reproducer and (apart from updating imports for DrHookTransformation and SCC in the loki-transform2.py script) it has worked for me with the current main version of Loki. Can you confirm that issue is resolved for you?
