### ISSUE TITLE
Generic approach for transformation specific settings in SchedulerConfig

### ISSUE THREAD

**Issue by MichaelSt98** [ecmwf-ifs/loki#28]
**Generic approach for transformation specific settings to avoid adding new keys flat into the scheduler config**

by introducing a `transformation_configs` key or similar as proposed by @reuterbal.

Consequently, transformation-specific sections (analogue to the routine-specific configs) could be declared, e.g.

```
[transformation_options]

[transformation_options.ParametriseTransformation]
dic2p = { NLEV = 137 }

[transformation_options.SccCufTransformation]
derived_types = [ 'TECLDP' ]
```

This could then be picked out in the scheduler's process routine and handed down to the transformation invocation:

```py
trafo_config = self.config.get(trafo_name, {})
...
transformation.apply(..., **trafo_config)
```

**Comment by mlange05** [comment]
Draft PR #191 should address this, so comments welcome.
