### ISSUE TITLE
Generic key-value options parameter in loki-transform.py

### ISSUE THREAD

**Issue by MichaelSt98** [ecmwf-ifs/loki#29]
As suggested by @reuterbal 

Generic key-value options parameter, essentially a dict of named options that can be handed as kwargs to the transformation. This can be achieved by using [tuples as multi-value options](https://click.palletsprojects.com/en/8.1.x/options/#tuples-as-multi-value-options).

```py
@click.option('--option', '-o', type=(str, str),
              type=click.Tuple([str, str]), multiple=True,
              help='Specify transformation options as key-value pairs')
```

**Comment by reuterbal** [comment]
I think the config file capabilities to parameterise transformations that we have now could be considered as fulfilling this requirement? (Cc @mlange05 )

**Comment by mlange05** [comment]
I'd think so. Happy to close this, if you agree.
