### ISSUE TITLE
Wrong parsing (at configure) of the  space sign  prevents Loki from attributing the type

### ISSUE THREAD

**Issue by piotrows** [ecmwf-ifs/loki#318]
This is wrong:
TYPE (DIMENSION_TYPE) , INTENT (IN)    :: KDIM
TYPE (STATE_TYPE)     , INTENT (IN)    :: STATE_T0
TYPE (AUX_TYPE)       , INTENT (IN)    :: PAUX
This works correctly:
TYPE (DIMENSION_TYPE) , INTENT(IN)    :: KDIM
TYPE (STATE_TYPE)     , INTENT(IN)    :: STATE_T0
TYPE (AUX_TYPE)       , INTENT(IN)    :: PAUX

Loki error message is ambiguous:
RuntimeError: Unable to find the module declaring DEFERRED.

**Comment by reuterbal** [comment]
Thanks, issue is confirmed and fixed in #323
