### ISSUE TITLE
REGEX frontend hangs if `END` is missing `SUBROUTINE`

### ISSUE THREAD

**Issue by mlange05** [ecmwf-ifs/loki#37]
While the following coding style should rightly be discouraged(!), it is legal Fortran, and causes the REGEX frontend to start spinning indefinitely and thus hang. The following MFE demonstrates this:
 
```
In [25]: fcode = """
subroutine some_routine(a)
  real, intent(in) :: a
end 
"""
Sourcefile.from_source(fcode, frontend=REGEX)
```
Of course, turning the final line into `end subroutine`, even without the name side-steps this, but .... Fortran...

**Comment by reuterbal** [comment]
I would argue not to support this notation and instead consider this broken Fortran. It's arguable whether we should allow missing procedure names in the `END`, but `SUBROUTINE` is mandatory in my view. To catch problems like this, I've added a regex frontend timeout utility with a generous default timeout.
