### ISSUE TITLE
problem with procedure pointers

### ISSUE THREAD

**Issue by npenigaud** [ecmwf-ifs/loki#393]
Procedure pointers are used in recent versions of the semi-implicit. However, the following leads to a bug in Loki :
spcmnew_pb.F90:
```fortran
SUBROUTINE SPCMNEW(YDGEOMETRY)

USE SPSI_MODNEW, ONLY : SPNSI
IMPLICIT NONE
PROCEDURE(SPNSI), POINTER :: SPNSIPTR
END SUBROUTINE SPCMNEW
```
launch.py:
```python
from loki import Sourcefile,fgen
source=Sourcefile.from_file('spcmnew_pb.F90',preprocess=True)
spcmnew=source['spcmnew']
print(fgen(spcmnew.spec))
```
(SPNSI is an abstract interface for a subroutine, included in spsi_modnew.F90).

**Comment by reuterbal** [comment]
Thanks for reporting this, I can reproduce the problem:
```py
from loki import Sourcefile
fcode = """
SUBROUTINE SPCMNEW
USE SPSI_MODNEW, ONLY : SPNSI
IMPLICIT NONE
PROCEDURE(SPNSI), POINTER :: SPNSIPTR
END SUBROUTINE SPCMNEW
"""
source = Sourcefile.from_source(fcode)
print(source.to_fortran())
```

This fails with an assertion in the `fgen` backend because the type information for `SPNSI` is missing:
```
File "/.../main/loki/backend/fgen.py", line 406, in visit_ProcedureDeclaration
    assert all(isinstance(t.dtype, ProcedureType) for t in types)
```

It works correctly if the type definition is provided to Loki, as in the following example:
```py
fcode_module = """
MODULE SPSI_MODNEW
IMPLICIT NONE
INTERFACE
  SUBROUTINE SPNSI
  END SUBROUTINE SPNSI
END INTERFACE
END MODULE SPSI_MODNEW
"""
fcode = "..."
module = Sourcefile.from_source(fcode_module)
source = Sourcefile.from_source(fcode, definitions=module.definitions)
print(source.to_fortran())
```
This produces the correct output:
```
SUBROUTINE SPCMNEW ()
  USE SPSI_MODNEW, ONLY: SPNSI
  IMPLICIT NONE
  PROCEDURE(SPNSI), POINTER :: SPNSIPTR
END SUBROUTINE SPCMNEW
```

The fix is to allow also deferred type information for the procedure interface, for which the following seems to suffice:
```diff
diff --git a/loki/backend/fgen.py b/loki/backend/fgen.py
index 5ca129cf..090e3c3b 100644
--- a/loki/backend/fgen.py
+++ b/loki/backend/fgen.py
@@ -403,12 +403,15 @@ class FortranCodegen(Stringifier):
         # TODO: We can't fully compare procedure types, yet, but we can make at least sure
         # names match and other declared attributes are compatible
         ignore = ['dtype', 'shape', 'dimensions', 'symbols', 'source', 'initial']
-        assert all(isinstance(t.dtype, ProcedureType) for t in types)
+        assert all(isinstance(t.dtype, ProcedureType) or t.dtype == BasicType.DEFERRED for t in types)
         assert all(t.compare(types[0], ignore=ignore) for t in types)
         if isinstance(o.interface, DataType):
             assert all(t.dtype.return_type.dtype == o.interface for t in types)
         elif o.interface is not None:
-            assert all(t.dtype.name == o.interface for t in types)
+            if types[0].dtype == BasicType.DEFERRED:
+                assert all(t.dtype == BasicType.DEFERRED for t in types)
+            else:
+                assert all(t.dtype.name == o.interface for t in types)

         if o.external:
             # This is an EXTERNAL statement (i.e., a kind of forward declaration)
```

@npenigaud Can you please confirm that the fix works for you? Then I will file a PR with these changes later.

**Comment by npenigaud** [comment]
Yes, the fix works for me, thanks. 
Regards, 
N. Penigaud 


De: "Balthasar Reuter" ***@***.***> 
À: "ecmwf-ifs/loki" ***@***.***> 
Cc: "Nicolas Penigaud" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Jeudi 10 Octobre 2024 09:34:16 
Objet: Re: [ecmwf-ifs/loki] problem with procedure pointers (Issue #393) 





Thanks for reporting this, I can reproduce the problem: 
from loki import Sourcefile fcode = """ SUBROUTINE SPCMNEW USE SPSI_MODNEW, ONLY : SPNSI IMPLICIT NONE PROCEDURE(SPNSI), POINTER :: SPNSIPTR END SUBROUTINE SPCMNEW """ source = Sourcefile . from_source ( fcode ) print ( source . to_fortran ()) 


This fails with an assertion in the fgen backend because the type information for SPNSI is missing: 
File "/.../main/loki/backend/fgen.py", line 406, in visit_ProcedureDeclaration
    assert all(isinstance(t.dtype, ProcedureType) for t in types) 


It works correctly if the type definition is provided to Loki, as in the following example: 
fcode_module = """ MODULE SPSI_MODNEW IMPLICIT NONE INTERFACE SUBROUTINE SPNSI END SUBROUTINE SPNSI END INTERFACE END MODULE SPSI_MODNEW """ fcode = "..." module = Sourcefile . from_source ( fcode_module ) source = Sourcefile . from_source ( fcode , definitions = module . definitions ) print ( source . to_fortran ()) 


This produces the correct output: 
SUBROUTINE SPCMNEW ()
  USE SPSI_MODNEW, ONLY: SPNSI
  IMPLICIT NONE
  PROCEDURE(SPNSI), POINTER :: SPNSIPTR
END SUBROUTINE SPCMNEW 


The fix is to allow also deferred type information for the procedure interface, for which the following seems to suffice: 
diff --git a/loki/backend/fgen.py b/loki/backend/fgen.py index 5ca129cf..090e3c3b 100644 --- a/loki/backend/fgen.py +++ b/loki/backend/fgen.py @@ -403,12 +403,15 @@ class FortranCodegen(Stringifier):
         # TODO: We can't fully compare procedure types, yet, but we can make at least sure
         # names match and other declared attributes are compatible
         ignore = ['dtype', 'shape', 'dimensions', 'symbols', 'source', 'initial'] - assert all(isinstance(t.dtype, ProcedureType) for t in types) + assert all(isinstance(t.dtype, ProcedureType) or t.dtype == BasicType.DEFERRED for t in types) assert all(t.compare(types[0], ignore=ignore) for t in types)
         if isinstance(o.interface, DataType):
             assert all(t.dtype.return_type.dtype == o.interface for t in types)
         elif o.interface is not None: - assert all(t.dtype.name == o.interface for t in types) + if types[0].dtype == BasicType.DEFERRED: + assert all(t.dtype == BasicType.DEFERRED for t in types) + else: + assert all(t.dtype.name == o.interface for t in types) if o.external:
             # This is an EXTERNAL statement (i.e., a kind of forward declaration) 


[ https://github.com/npenigaud | @npenigaud ] Can you please confirm that the fix works for you? Then I will file a PR with these changes later.
