### ISSUE TITLE
Some metaclass conflict using loki.types.DataType and IntEnum with Python 3.11

### ISSUE THREAD

**Issue by meteospike** [ecmwf-ifs/loki#69]
While loading basic loki types, file `enum.py` raise `too many data types for 'BasicType': {<class 'int'>, <class 'loki.types.DataType'>}`

This occurs in the calling tree of the metaclass `EnumType` (more than one datatype found).

**Comment by reuterbal** [comment]
Thanks. I have observed the same, which is a change in behaviour with Python 3.12. I will take care of fixing this soon.
As we don't support or test Python 3.12, yet, please switch to an older Python version in the meantime.

**Comment by meteospike** [comment]
Thanks, I'm indeed currently using Python 3.10. Testing the install with Python 3.11 was just a matter of prospect, mainly because of the claim of the impressive efficiency of this new release... Anyway, it may be hard to get spectacular improvement on such a code (parsing, AST), with low amount of calculations.
